### ISSUE TITLE
Margin: auto in container cuts off width of locations image

### ISSUE THREAD

**Issue by jzhu01** [chrisgrazioli/prj-rev-bwfs-tea-cozy#1]
Seen here: https://github.com/chrisgrazioli/prj-rev-bwfs-tea-cozy/blob/master/teacozy/resources/css/style.css#L40

It seems like by setting width to 90% you are only affecting the locations div. I recommend removing this line :)

**Comment by chrisgrazioli** [comment]
yeah I don't see why I had hat in there
