### ISSUE TITLE
justify-content and background-repeat not necessary on mission

### ISSUE THREAD

**Issue by jzhu01** [chrisgrazioli/prj-rev-bwfs-tea-cozy#2]
Seen here: https://github.com/chrisgrazioli/prj-rev-bwfs-tea-cozy/blob/master/teacozy/resources/css/style.css#L44-L52

The justify-content is not changing the display on the screen, and the background-repeat also does not have an effect. I think you can remove these!

**Comment by chrisgrazioli** [comment]
The background-repeat only would have made a difference if the height of .mission wasn't declared?
