### ISSUE TITLE
featured needs a padding top

### ISSUE THREAD

**Issue by jzhu01** [chrisgrazioli/prj-rev-bwfs-tea-cozy#3]
You also can remove these stylings as they have no effect: 
https://github.com/chrisgrazioli/prj-rev-bwfs-tea-cozy/blob/master/teacozy/resources/css/style.css#L61-L63

But if you give feature a padding top that will give some space between this section and the previous.

**Comment by chrisgrazioli** [comment]
this is because the text-align: center in html{} ?
